"""
Stadium Pulse AI Shared Utilities (`helpers.py`).

WHY: Isolating string sanitization, markdown JSON extraction, and pure mathematical helpers
in `app/utils/` guarantees modular separation of concerns and keeps core domain classes concise.
"""

import re
from typing import Optional


def extract_clean_json_from_markdown(raw_text: str) -> str:
    """
    Extracts a valid JSON block from markdown code fences if present.

    Args:
        raw_text (str): Raw string output generated by LLMs or external systems.

    Returns:
        str: Sanitized string containing only the JSON payload, ready for schema parsing.

    WHY: Protects structured parsers against LLMs prematurely wrapping valid JSON inside ```json ... ``` blocks.
    """
    if not raw_text or not raw_text.strip():
        return ""
    match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw_text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return raw_text.strip()


def sanitize_csv_payload(payload: Optional[str]) -> str:
    """
    Validates and cleans raw CSV text input received via REST endpoints.

    Args:
        payload (Optional[str]): Raw string submitted in batch requests.

    Returns:
        str: Strip-cleaned multi-line string.

    Raises:
        ValueError: If the payload is empty or whitespace-only (Bouncer Pattern early return).

    WHY: Enforces early validation boundaries before stream readers begin processing multi-row datasets.
    """
    if not payload or not payload.strip():
        raise ValueError("CSV payload string cannot be empty or whitespace-only.")
    return payload.strip()
